### ISSUE TITLE
Custom cam for shaders

### ISSUE THREAD

**Issue by Rice1367** [riconuts/troll-engine#18]
### Describe your problem here.

ye
Sorry if this is a stupid question, but I was trying to add a shader as a background, but I was having some problems because some Lua functions for shaders don't work and don't seem to be in the engine either. I tried creating a camera behind camGame but it doesn't seem to work as it ends up breaking the other shaders I had (I guess the whole script stops working w). I also tried creating an object as a background to apply the shader to, but either the same thing happened or it just didn't work (I'm not very good with hscript, but I tried looking in several places before asking)
This is the script I tried to use to create the custom camera and then how the shader is applied to the entire camGame. It works on most cameras (except StageUnderlay because I didn't quite understand what that was), but it always goes on top of all objects

``` hx
var camBehind:FlxCamera = new FlxCamera();
camBehind.zoom = cam.camGame.zoom;
camBehind.bgColor = 0xFFFFFFFF;
game.camGame.bgColor = 0x00000000;
FlxG.cameras.remove(game.camGame, false);
FlxG.cameras.remove(game.camStageUnderlay, false);
FlxG.cameras.remove(game.camHUD, false);
FlxG.cameras.remove(game.camOverlay, false);
FlxG.cameras.remove(game.camOther, false);
FlxG.cameras.add(camBehind, false);
FlxG.cameras.add(game.camGame, true);
FlxG.cameras.add(game.camStageUnderlay, false);
FlxG.cameras.add(game.camHUD, false);
FlxG.cameras.add(game.camOverlay, false);
FlxG.cameras.add(game.camOther, false);
setVar('camBehind', camBehind);
game.camGame.bgColor = 0x00000000;

function onCreate(){
    game.camBehind.setFilter([new ShaderFilter(redHole)]);
}

// then ded
```
![image](https://github.com/riconuts/troll-engine/assets/143020225/343fcfb9-276d-425d-8e5b-935f345d4530)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by riconuts** [comment]
Ok, just so you know, Lua isn't really supported and it's just a thing we left on the engine out of generosity, so anything that uses psych's functions added past v0.5.2h will fail, including shaders, same thing with the hscript implementation, this engine has it's own so the setVar function here isn't defined and will cause the script to stop. 
(The equivalent of 'setVar()' here would be 'script.set()' so make sure to replace that function like this)
>  script.set('camBehind', camBehind);

Besides that I can't help you much!!! I don't any knowledge or access to the shader code or your any script of your mod!!! 
If what you sent here is the full script then the only other issue I see is that 'redHole' (on the onCreate function) isn't defined anywhere which would also causes an error. if you have a shader called redHole on your mod folder then you would have to change it that line to  

> game.camBehind.setFilter([new ShaderFilter(newShader('redHole'))]);

Oh and the stage underlay camera is used for the stage darkness option, it has it's own camera so that you don't accidentally add anything on top of it.

**Comment by Rice1367** [comment]
Oh, thanks so much for the clarification and I'm sorry if I sounded a little stupid. I tried to recreate the script in a somewhat simpler and faster way but I forgot to add the definition of redHole that I had in the original. But other than that, that's all I used, just a few more shaders (the reason I wanted to simplify it), but the same problem occurs even without them. Thanks again for the clarifications and help, although unfortunately I couldn't solve it, but I'll see if I can solve it by learning something more about hscript, I don't want to be so annoying by asking about it a lot 
In any case, I thank you for your attention and I wish you luck in this and other projects, good day or night

**Comment by Rice1367** [comment]
Well, to end this on a happy ending, I had a silly idea.
Instead of making a new camera (just because I'm bad at hscript), I'll just move all the characters and stage to camStageUnderlay (dumb idea, but at least it worked)
It didn't solve my doubt but it did solve my problem
